Session timeout RH link defect
ONSdigital/eq-questionnaire-runner pull request #1072
Opened 2023-03-27 14:33 UTC by rmccar

### What is the context of this PR?
Fixes session timeout page link to take the base url from the cookie if it exists.

### How to review
Open a schema with a `Account Service URL` set. Check that the session expired page uses this as a base url for the page link.

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2023-03-27 14:35 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Defect: Link to re-enter AUC following a session timeout in pre-prod and Int are pointing to Prod RH-UI](https://trello.com/c/Mtpxe4HM/5638-defect-link-to-re-enter-auc-following-a-session-timeout-in-pre-prod-and-int-are-pointing-to-prod-rh-ui)

2023-04-05 12:42 UTC, kylelawsonAND commented
Link appears to redirect correctly locally (no page to load of course but url is correct I think). Can't test in a different env but otherwise all looks sensible, unofficial ✅  from me

2023-04-05 13:22 UTC, petechd requested changes
You need to change the base branch for this PR to main.

2023-04-05 15:13 UTC, rmccar commented
> You need to change the base branch for this PR to main.

Yeah I know I will change it when my other PR goes in. Because I branched off my other PR this allows me to see the changes without the ones from that branch at the moment

2023-04-13 08:48 UTC, MebinAbraham commented on app/routes/errors.py
>      )
Actually this won't work as the base url will be used by both types in this case. We actually don't need any changes in runner. You need to update the runner terraform and eq pipelines to add in `ACCOUNT_SERVICE_BASE_URL_SOCIAL`, at the moment, it doesn't set it, therefore it defaults to prod.

2023-04-13 12:01 UTC, closed without merging