Update Prepop branch with changes from main (#1117)
ONSdigital/eq-questionnaire-runner pull request #1153
Opened 2023-07-04 14:10 UTC by MebinAbraham

### What is the context of this PR?
Updates `feature-prepop` with changes from `main`.

### How to review
Ensure the changes looks correct + all tests pass

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2023-07-04 14:48 UTC, katie-gardner requested changes
I think merge conflict resolution might have resulted in Petes changes being omitted - can't see his fix to `jinja_filters.py` anymore which I think is why the test is failing

2023-07-04 15:21 UTC, MebinAbraham commented
> I think merge conflict resolution might have resulted in Petes changes being omitted - can't see his fix to `jinja_filters.py` anymore which I think is why the test is failing

Up bad merge will sort, unit test picked it up 👍

2023-07-05 08:57 UTC, katie-gardner approved these changes

2023-07-05 11:16 UTC, kylelawsonAND approved these changes
LGTM - tests passing as normal, changes look like they've come through okay after merge

2023-07-05 11:31 UTC, merged