Add UKHSA ONS theme
ONSdigital/eq-questionnaire-runner pull request #1225
Opened 2023-10-09 15:20 UTC by katie-gardner

### What is the context of this PR?
This PR adds the UKHSA ONS theme.

[Validator PR ](https://github.com/ONSdigital/eq-questionnaire-validator/pull/220) for allowing the theme

### How to review
Use `test_theme_ukhsa_ons.json` and check that the logos at the top show correctly. Check that implementation is similar to that of other themes.

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2023-10-09 15:23 UTC, katie-gardner commented
![](https://github.trello.services/images/mini-trello-icon.png) [New theme for UKHSA Branding (WCIS) (1 SP)](https://trello.com/c/6axFtNLI/5913-new-theme-for-ukhsa-branding-wcis-1-sp)

2023-10-09 15:41 UTC, katie-gardner commented on scripts/run_validator.sh
> +tag=add-ukhsa-ons-theme
reminder to revert

2023-10-09 15:57 UTC, rmccar requested changes
The logos dont quite line up. I think we should either make the ONS one a bit bigger or add the `ons-u-mb-xs` class to it

![Screenshot 2023-10-09 at 16 55 15](https://github.com/ONSdigital/eq-questionnaire-runner/assets/42928680/ec3a2481-fdc3-4365-97b9-ea6677c85022)

Other than that looks good

2023-10-09 16:42 UTC, MebinAbraham commented on schemas/test/en/test_theme_ukhsa_ons.json
> +    "title": "Test Winter Coronavirus Infection Study",
I would remove this from the title. Just name it after UKHSA. The survey isn't important, they may run many.

2023-10-10 08:27 UTC, katie-gardner commented on templates/errors/_base.html
>  {% set SURVEY_TYPES_HEALTH = ["health"] %}
Ah thanks, fixed

2023-10-10 08:28 UTC, katie-gardner commented
> The logos dont quite line up. I think we should either make the ONS one a bit bigger or add the `ons-u-mb-xs` class to it
> 
> ![Screenshot 2023-10-09 at 16 55 15](https://user-images.githubusercontent.com/42928680/273637206-ec3a2481-fdc3-4365-97b9-ea6677c85022.png)
> 
> Other than that looks good

Thanks Rich - have tried adding the margin class you suggested, let me know what you think?

2023-10-10 08:32 UTC, rmccar commented
> > The logos dont quite line up. I think we should either make the ONS one a bit bigger or add the `ons-u-mb-xs` class to it
> > ![Screenshot 2023-10-09 at 16 55 15](https://user-images.githubusercontent.com/42928680/273637206-ec3a2481-fdc3-4365-97b9-ea6677c85022.png)
> > Other than that looks good
> 
> Thanks Rich - have tried adding the margin class you suggested, let me know what you think?

Looks much better 👍

2023-10-10 08:32 UTC, rmccar approved these changes

2023-10-10 09:18 UTC, MebinAbraham commented
> > > The logos dont quite line up. I think we should either make the ONS one a bit bigger or add the `ons-u-mb-xs` class to it
> > > ![Screenshot 2023-10-09 at 16 55 15](https://user-images.githubusercontent.com/42928680/273637206-ec3a2481-fdc3-4365-97b9-ea6677c85022.png)
> > > Other than that looks good
> > 
> > 
> > Thanks Rich - have tried adding the margin class you suggested, let me know what you think?
> 
> Looks much better 👍

The logo sizing is currently inconsistent. Is the header sizing dependent on the max width of the logos @rmccar. There doesn't seem to be a min height?.

This compared to `desnz_ni` is smaller but matches the header size of dbt_dsit_ni. The headers should all be the same height ideally. 

Should they be aligned vertically?. This is what I can see at the moment. But this isn't centered among themselves.
<img width="630" alt="image" src="https://github.com/ONSdigital/eq-questionnaire-runner/assets/35296336/733619ae-04bf-4557-89c2-d91ae2a42c5b">

2023-10-10 09:30 UTC, rmccar commented
> > > > The logos dont quite line up. I think we should either make the ONS one a bit bigger or add the `ons-u-mb-xs` class to it
> > > > ![Screenshot 2023-10-09 at 16 55 15](https://user-images.githubusercontent.com/42928680/273637206-ec3a2481-fdc3-4365-97b9-ea6677c85022.png)
> > > > Other than that looks good
> > > 
> > > 
> > > Thanks Rich - have tried adding the margin class you suggested, let me know what you think?
> > 
> > 
> > Looks much better 👍
> 
> The logo sizing is currently inconsistent. Is the header sizing dependent on the max width of the logos @rmccar. There doesn't seem to be a min height?.
> 
> This compared to `desnz_ni` is smaller but matches the header size of dbt_dsit_ni. The headers should all be the same height ideally.
> 
> Should they be aligned vertically?. This is what I can see at the moment. But this isn't centred among themselves. <img alt="image" width="630" src="https://user-images.githubusercontent.com/35296336/273844845-733619ae-04bf-4557-89c2-d91ae2a42c5b.png">

When you say header size do you mean the height of the white part of the header? Because yes thats based on the hight of the logos. There is a minimum though.

With so many different logos created in different ways its fiddly to get them all the right size. Some have really different designs too so need to be a certain size to be readable. Plus we have stacked and non stacked versions of some logos like the ONS one. There seems to be no standardisation when creating them and when Ive done these in the past Ive had to tidy up and get the logos looking a similar size myself by hand and I don't have any software to do it. I helped Katie out with this yesterday because the logo attached to the card doesn't work at all.

I think really we need a designer to go over all the logos to standardise and optimise them.

On those logos being aligned that was the best way of doing it with the DS utility classes we have. Another option would be to potentially edit the ONS logo to make the whitespace around it a bit bigger in order to pad it out. I can have a look at that if you wanted?

2023-10-10 09:47 UTC, MebinAbraham commented on app/survey_config/social_survey_config.py
> +    ) + read_file("./templates/assets/images/ukhsa-logo-stacked.svg")
Got confirmation, the UKHSA logo needs to go first.

2023-10-10 09:52 UTC, MebinAbraham commented
> When you say header size do you mean the height of the white part of the header? Because yes thats based on the hight of the logos. There is a minimum though.

How is that currently calculated?. Is it the largest logo etc?. At the moment, it doesn't seem consistent. 

For now, we can get it in as is. Can you raise a card to review these from a design perspective. Is there any change needed in DS?.

2023-10-10 09:54 UTC, rmccar commented
> > When you say header size do you mean the height of the white part of the header? Because yes thats based on the hight of the logos. There is a minimum though.
> 
> How is that currently calculated?. Is it the largest logo etc?. At the moment, it doesn't seem consistent.
> 
> For now, we can get it in as is. Can you raise a card to review these from a design perspective. Is there any change needed in DS?.

Yeah itll be the largest one that its based on.

Yeah Ill raise a card and add it to the backlog. No changes in the DS needed as all the logos we use are in runner

2023-10-10 16:34 UTC, merged