Add transforms to support users with matching names
ONSdigital/eq-questionnaire-runner pull request #295
Opened 2020-09-18 13:30 UTC by iwootten

### What is the context of this PR?

Adds a number of transforms to placeholders for displaying middle names when first and last name match.

NB. Originally I had used a new source of "list_item_id" to return the list_Item_id, but this seemed very specific and after discussion felt it better we add a "location" source. The renderer already takes both a list_item_id and location and we actually return that of list_item_id in the new transforms - to use location requires significant change to the existing context design (as they don't always have the property) which didn't seem required for this feature. If we ever have a need for other location properties in transforms, then we can perhaps look at refactoring contexts to support them.

### How to review 

Describe the steps required to test the changes (include screenshots if appropriate).

2020-09-18 13:30 UTC, iwootten commented
![](https://github.trello.services/images/mini-trello-icon.png) [[T] Resolve name to be displayed when duplicate names exist (M)](https://trello.com/c/cIBH9hWa/4112-t-resolve-name-to-be-displayed-when-duplicate-names-exist-m)

2020-09-21 07:43 UTC, ajmaddaford requested changes

2020-09-21 08:20 UTC, iwootten commented on test_schemas/en/test_list_collector_same_name_items.json
> +                                                            "identifier": "list_item_id"
I think list will be reserved, so we'd need to use something else `list_to_check`?

2020-09-21 12:03 UTC, ajmaddaford commented on test_schemas/en/test_list_collector_same_name_items.json
> +                                                        "include_middle_name": { "source": "previous_transform" },
`include_middle_name` should be `include_middle_names` to align with the `middle_names` property.

2020-09-22 10:10 UTC, ajmaddaford approved these changes

2020-09-22 10:48 UTC, MebinAbraham approved these changes

2020-09-22 10:48 UTC, MebinAbraham commented on scripts/run_validator.sh
> +tag=resolve-name-display
Reminder to revert before merge.

2020-09-22 12:04 UTC, merged