Update error for mutually exclusive
ONSdigital/eq-questionnaire-runner pull request #308
Opened 2020-09-25 12:25 UTC by iwootten

### What is the context of this PR?

All mutually exclusive mandatory questions need to change to when only checkboxes are used for each answer type: 

- "Select at least one answer"
- "Select at least one answer to {question} (Using screenreaders)"

They should remain as: 

- "Enter an answer to continue" when answers of differing types are used.

### How to review 

Use the `test_mutually_exclusive` schema to confirm that errors displayed as expected. (New mandatory with differing answer type added)

2020-09-25 12:27 UTC, iwootten commented
![](https://github.trello.services/images/mini-trello-icon.png) [[P] Update error message for mutually exclusive questions (s)](https://trello.com/c/3Lt2DA6W/4128-p-update-error-message-for-mutually-exclusive-questions-s)

2020-09-28 07:07 UTC, ajmaddaford approved these changes

2020-09-28 07:07 UTC, ajmaddaford commented on tests/app/forms/test_questionnaire_form.py
> +                ),
I think this test should test the standard error message rather than the checkbox one.

2020-09-28 08:55 UTC, MebinAbraham requested changes
Looks good, just a minor comment.

2020-09-28 08:55 UTC, MebinAbraham commented on app/forms/questionnaire_form.py
> +        )
Can we make this consistent with `is_mandatory` and call this `is_only_checkboxes` or `are_all_checkboxes`?

2020-09-28 09:57 UTC, MebinAbraham approved these changes

2020-09-28 10:02 UTC, merged