Align previous link style with Breadcrumbs
ONSdigital/eq-questionnaire-runner pull request #323
Opened 2020-09-30 10:41 UTC by rmccar

### What is the context of this PR?
Change previous links to use a single breadcrumb instead. Needs (this PR)[https://github.com/ONSdigital/design-system/pull/1052] to be merged and released in DS first though.

### How to review 
Check previous links have been updated with the correct style and they work exactly as they did previously.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2020-10-15 11:15 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #802: Align previous link used in questionnaires with breadcrumbs, and consider use of back links in transactions](https://trello.com/c/UOFhPI2I/4186-issue-802-align-previous-link-used-in-questionnaires-with-breadcrumbs-and-consider-use-of-back-links-in-transactions)

2020-10-19 06:42 UTC, ajmaddaford approved these changes

2020-10-19 06:42 UTC, ajmaddaford commented on templates/layouts/_base.html
> +      }
```suggestion
      {
        "url": previous_location_url,
        "id": "top-previous",
        "text": _("Previous"),
        "attributes": {
          "data-ga": 'click',
          "data-ga-category": 'Navigation',
          "data-ga-action": 'Previous link click'
        }
      }
```

2020-10-19 08:47 UTC, LJBabbage requested changes
I wasn't expected such a small font, its coming up as 9.33pt, is that right?

![image](https://user-images.githubusercontent.com/14179817/96422629-2bd2f180-11f0-11eb-9739-fd47c8235142.png)

2020-10-19 09:14 UTC, rmccar commented
> I wasn't expecting such a small font, it's coming up as 9.33pt, is that right?
> 
> ![image](https://user-images.githubusercontent.com/14179817/96422629-2bd2f180-11f0-11eb-9739-fd47c8235142.png)
> 

Yeah this is the style that is used for breadcrumbs and back links will now look the same

2020-10-19 09:21 UTC, LJBabbage approved these changes
Cool, all good then

2020-10-19 09:21 UTC, merged