Update Individual Response button on Interstitial page
ONSdigital/eq-questionnaire-runner pull request #329
Opened 2020-10-01 08:50 UTC by berroar

### What is the context of this PR?
The `Request separate census` button on the Individual Response interstitial page should be a '[Call to action](https://ons-design-system.netlify.app/components/button/#call-to-action)' button with chevron, using the `button` type anchor link with URL.

I have left the url field empty as I'm not sure we can set a value for this? The IR journey is still working however.

### How to review 
Use the `test_individual_response` to check the change

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2020-10-01 08:54 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change call to action on /individual-response/ launcher from form sumbit button to anchor link](https://trello.com/c/DwnsWQdo/4188-change-call-to-action-on-individual-response-launcher-from-form-sumbit-button-to-anchor-link)

2020-10-01 12:20 UTC, ajmaddaford commented on templates/individual_response/interstitial.html
> +            "url": "",
The chevron is missing from the button the as the `url` property is empty. For this to work we need to remove the `POST` from the endpoint and on a GET request determine the URL for the next page. That URL should be used here, and will be whatever we currently redirect to on the POST request.

2020-10-02 08:43 UTC, ajmaddaford requested changes

2020-10-02 08:43 UTC, ajmaddaford commented on app/views/handlers/individual_response.py
> +        self._list_name = self._schema.get_individual_response_list()
`self._list_name` is already set in the init.
```suggestion
```

2020-10-02 08:43 UTC, ajmaddaford commented on app/views/handlers/individual_response.py
> +
There is a lot going on in this method now. I think we should create `get_previous_location_url` and `get_next_location_url` methods, and call them from here.

2020-10-02 08:43 UTC, ajmaddaford commented on tests/integration/individual_response/test_individual_response.py
> +        return submit_button.attrs["href"]
This method should be consistent with the `individual_section_link` and `individual_response_link` methods. It should be defined as a `@property` and named something like `individual_response_start_link`.

2020-10-02 11:48 UTC, ajmaddaford requested changes

2020-10-02 11:48 UTC, ajmaddaford commented on app/views/handlers/individual_response.py
> +            return url_for("questionnaire.get_questionnaire")
Same as the comment above about the `elif` and `else`.

2020-10-02 11:48 UTC, ajmaddaford commented on app/views/handlers/individual_response.py
>          )
As this is only used in the second conditional, these lines should be moved there.

2020-10-02 13:23 UTC, ajmaddaford approved these changes

2020-10-02 13:54 UTC, LJBabbage approved these changes
The moving around of stuff confusion me a touch, but it looks ok and works as expected

2020-10-02 14:02 UTC, petechd approved these changes

2020-10-02 14:02 UTC, merged