Make the summary page submit button text customisable
ONSdigital/eq-questionnaire-runner pull request #387
Opened 2020-11-04 08:58 UTC by berroar

### What is the context of this PR?
Fixes an issue where the `Submit` button on the Summary page was not picking up custom content from schemas using `content.submit_button`

### How to review 
Use the `test_summary_with_submission_text` schema to ensure the submit button content matches the content set in the schema.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2020-11-04 09:26 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [CE & Individual - submit button says 'Submit answers' when should say 'Submit census'](https://trello.com/c/FL2WBbJc/4285-ce-submit-button-says-submit-answers-when-should-say-submit-census)

2020-11-04 12:45 UTC, petechd requested changes
I think summary page title change is still missing (templates/summary.html). Should be "Submit census - Census 2021" not "Summary - Census 2021".

2020-11-04 14:00 UTC, petechd approved these changes

2020-11-04 15:23 UTC, MebinAbraham requested changes

2020-11-04 15:23 UTC, MebinAbraham commented on templates/summary.html
> +{% set summary_page_title = _("Submit census") %}
This should come from the context.
```suggestion
{% set summary_page_title = content.title %}
```

2020-11-04 15:33 UTC, MebinAbraham commented on tests/integration/questionnaire/test_questionnaire_page_titles.py
> +        self.assertEqualPageTitle("Submit census - Census 2021")
```suggestion
        self.assertEqualPageTitle("Check your answers and submit - Census 2021")
```

2020-11-05 10:07 UTC, MebinAbraham approved these changes

2020-11-05 10:11 UTC, merged