Remove IR link from non IR list remove page
ONSdigital/eq-questionnaire-runner pull request #452
Opened 2020-12-07 11:53 UTC by LJBabbage

### What is the context of this PR?
The IR link on remove list person should only appear on IR lists.

### How to review 
Using test_individual_response add a visitor and then try to remove them. You should get the "If you can’t answer questions for this person" message and link

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2020-12-07 14:11 UTC, JamesGardiner requested changes

2020-12-07 14:11 UTC, JamesGardiner commented on app/views/handlers/list_remove_question.py
>              return True
```suggestion
		return self.parent_block["for_list"] == self._schema.get_individual_response_list()
```

2020-12-07 15:26 UTC, MebinAbraham approved these changes

2020-12-08 07:18 UTC, JamesGardiner approved these changes

2020-12-08 07:50 UTC, petechd approved these changes

2020-12-08 09:04 UTC, merged