Add print button to the view submitted response page
ONSdigital/eq-questionnaire-runner pull request #657
Opened 2021-09-07 11:28 UTC by berroar

### What is the context of this PR?

Adds a `Print answers` button to the `view-submitted-response` page.

### How to review 

Use the `test_view_submitted_response` schema to test this change

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2021-09-07 11:33 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to print (1 SP)](https://trello.com/c/LppdlOi1/4839-ability-to-print-1-sp)

2021-09-07 12:36 UTC, MebinAbraham commented on templates/view-submitted-response.html
> +    <br><br>
Instead of break tags, this should be done via CSS, the prototype set `u-mt-l` CSS classes on the summary.

2021-09-07 12:36 UTC, MebinAbraham commented on templates/view-submitted-response.html
> +        "buttonStyle": "print",
The button in the prototype is the small version, which can be done via `"classes": "btn--small",`

2021-09-07 13:09 UTC, MebinAbraham commented on templates/view-submitted-response.html
> +      <div class="u-mt-l">
You still want to keep the margin bottom, also this should really be added via the ons summary component, but we need to do some refactoring and clean up as section summary doesn't set these. For now, I think it is fine to add here.

2021-09-08 10:38 UTC, MebinAbraham commented on tests/functional/spec/features/view_submitted_response/view_submitted_response.js
> +    expect($(ViewSubmittedResponsePage.printButton()).getText()).to.equal("Print answers");
I think you should assert that it is rendered on the page via like `isDisplayed()`

2021-09-08 11:07 UTC, MebinAbraham approved these changes

2021-09-08 13:56 UTC, LJBabbage requested changes
We seem to only have positive checks in this story and the one previous unless I missed it. We really should be checking that content, including the print button isn't displayed after 45 minutes (naturally we would override that in the test to 0)

2021-09-08 15:30 UTC, MebinAbraham commented
> button isn't displayed after 45 minutes

We don't support that yet, we return a 404 atm as discussed in tech session. It will handled in https://trello.com/c/nYmiT9i0/4846-view-submitted-response-page-after-timeout

2021-09-09 07:49 UTC, LJBabbage commented
> > button isn't displayed after 45 minutes
> 
> We don't support that yet, we return a 404 atm as discussed in tech session. It will handled in https://trello.com/c/nYmiT9i0/4846-view-submitted-response-page-after-timeout

Probably need an out of scope on the original cards as it's not obvious and reviewing should be dependent on tech session attendance

2021-09-09 07:50 UTC, LJBabbage approved these changes

2021-09-09 08:00 UTC, merged