Update to DS version 45.1.0
ONSdigital/eq-questionnaire-runner pull request #762
Opened 2022-01-18 12:58 UTC by rmccar

### What is the context of this PR?
This PR will update Runner to DS version 45.1.0 which some other pieces of work require.

### How to review 
Tests pass and runner works as expected

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2022-01-18 13:23 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Introduce anchor link to summary page tables (2 SP)](https://trello.com/c/aNrekImJ/5064-introduce-anchor-link-to-summary-page-tables-2-sp)

2022-01-19 15:20 UTC, MebinAbraham commented on app/jinja_filters.py
> +            self.id = question["id"] + "-row-item"
The IDs shouldn't be suffixed. Also in both cases, we want to use the answer id but we only really need to set the answer id, if it is a row that can be edited, so:
```py
        if edit_link_text:
            self.id = answer["id"]
```

2022-01-25 09:26 UTC, MebinAbraham requested changes
The jinja filter test needs updating to ensure `id` is present in the output. Integration test can be done by the feature that uses this (so James' PR)

EDIT: Ignore, just seen the changes, didn't spot it.

2022-01-25 11:28 UTC, LJBabbage approved these changes

2022-01-25 11:29 UTC, jamesnunn approved these changes

2022-01-25 12:17 UTC, MebinAbraham approved these changes

2022-01-25 12:30 UTC, merged