Rewrite cloud task publishers tests using pytest
ONSdigital/eq-questionnaire-runner pull request #773
Opened 2022-01-25 09:59 UTC by petechd

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2022-01-25 11:45 UTC, petechd commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate cloud_tasks module to pytest framework (1 SP)](https://trello.com/c/TXZMao9x/5084-migrate-cloudtasks-module-to-pytest-framework-1-sp)

2022-01-25 15:47 UTC, MebinAbraham requested changes
Minor suggestions

2022-01-25 19:52 UTC, LJBabbage commented on tests/app/cloud_tasks/test_cloud_task_publishers.py
> +    cloud_task_publisher = CloudTaskPublisher()
You will need to take the patch as well (_get_explicit_environ_credentials) but this would slim down the code

2022-01-26 09:23 UTC, petechd commented on tests/app/cloud_tasks/test_cloud_task_publishers.py
> +    cloud_task_publisher = CloudTaskPublisher()
Removed all this to pytest fixture in newly created `conftest.py`, thanks!

2022-01-26 09:24 UTC, petechd commented on tests/app/cloud_tasks/test_cloud_task_publishers.py
> +    transaction_id=str(uuid4()),
Made them constants available on module level, modified functions accordingly.

2022-01-26 13:46 UTC, MebinAbraham approved these changes

2022-01-26 13:50 UTC, merged