Create functional tests 3
ONSdigital/eq-questionnaire-runner pull request #780
Opened 2022-01-31 17:03 UTC by jamesnunn

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review 
Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

2022-02-02 15:57 UTC, jamesnunn commented on tests/functional/spec/question_description.spec.js
> +    expect($(NameBlockPage.questionTitle()).getText()).to.contain("Answer the question\nGo on");
I didn’t get as far as inspecting the `<p>` elements for the description test if necessary I'll work on it but at least this gets hold of the content

2022-02-03 08:30 UTC, jamesnunn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create functional tests batch 3 (3 SP)](https://trello.com/c/imqcUzH3/5099-create-functional-tests-batch-3-3-sp)

2022-02-03 11:18 UTC, parimooa approved these changes
LGTM

2022-02-07 12:20 UTC, LJBabbage requested changes
Looks good, just a few tweaks

2022-02-07 12:20 UTC, LJBabbage commented on tests/functional/spec/radio_checkbox_descriptions.spec.js
> +      expect($(CheckboxBlockPage.newMethodsOfOrganisingExternalRelationshipsWithOtherFirmsOrPublicInstitutionsLabelDescription()).getText()).to.contain(
Blimey, that's some name

2022-02-07 12:20 UTC, LJBabbage commented on tests/functional/spec/question_description.spec.js
> +  it("Given a question description has been set in the schema as an array, it is displayed correctly as a newline-separated string", () => {
Just need to update to Given / When /Then

2022-02-07 12:20 UTC, LJBabbage commented on tests/functional/spec/radio_optional_with_detail_answer_optional.spec.js
> +    it("When no answer is provided, the expected answer is displayed", () => {
Just missing the then, and it might help if it said displayed on the summary. Same for the ones below

2022-02-07 14:07 UTC, jamesnunn commented on tests/functional/spec/radio_checkbox_descriptions.spec.js
> +      expect($(CheckboxBlockPage.newMethodsOfOrganisingExternalRelationshipsWithOtherFirmsOrPublicInstitutionsLabelDescription()).getText()).to.contain(
Indeed it is

2022-02-09 08:39 UTC, LJBabbage commented on tests/functional/spec/submit_with_custom_submission_text.spec.js
> +  it("Given a questionnaire with custom submission content has been completed, then the correct submission content should be displayed", () => {
Just one missing

2022-02-09 08:40 UTC, LJBabbage approved these changes
Just one Given / When /Then missing

2022-02-09 11:31 UTC, petechd approved these changes

2022-02-09 11:32 UTC, merged